module.exports = {
  apps: [
    {
      name: 'social-workbench',
      script: 'server/index.js',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: process.env.PORT || 3000,
        DATA_DIR: process.env.DATA_DIR || '/data',
        WORKBENCH_DB_DIR: process.env.WORKBENCH_DB_DIR || '/data/db',
        WORKBENCH_ACCOUNT_DB_MODE: process.env.WORKBENCH_ACCOUNT_DB_MODE || 'isolated',
        WORKBENCH_ACCOUNT_DATA_DIR: process.env.WORKBENCH_ACCOUNT_DATA_DIR || '/data/accounts',
        WORKBENCH_SEND_ENABLED: process.env.WORKBENCH_SEND_ENABLED || '0',
        WORKBENCH_CHANNEL_RUNTIME_REQUIRED: process.env.WORKBENCH_CHANNEL_RUNTIME_REQUIRED || '1',
        SSO_ENABLED: process.env.SSO_ENABLED || 'true',
        SSO_LOGIN_URL: process.env.SSO_LOGIN_URL || 'https://skyline-ark-sso.tyhark.com/login',
        SSO_LOGOUT_URL: process.env.SSO_LOGOUT_URL || 'https://skyline-ark-sso.tyhark.com/logout',
        SSO_REDIRECT_PARAM: process.env.SSO_REDIRECT_PARAM || 'redirect',
        SSO_LOGOUT_REDIRECT_PARAM: process.env.SSO_LOGOUT_REDIRECT_PARAM || 'redirect',
      },
      max_memory_restart: '512M',
      kill_timeout: 5000,
    },
    {
      name: 'social-workbench-login-worker',
      script: 'workers/service-login-worker.js',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        DATA_DIR: process.env.DATA_DIR || '/data',
        WORKBENCH_DB_DIR: process.env.WORKBENCH_DB_DIR || '/data/db',
        WORKBENCH_RAW_DB_PATH: process.env.WORKBENCH_RAW_DB_PATH || '/data/db/raw.sqlite',
        WORKBENCH_RUNTIME_DB_PATH: process.env.WORKBENCH_RUNTIME_DB_PATH || '/data/db/runtime.sqlite',
        WORKBENCH_OUTBOX_DIR: process.env.WORKBENCH_OUTBOX_DIR || '/data/outbox',
        WORKBENCH_ACCOUNT_DB_MODE: process.env.WORKBENCH_ACCOUNT_DB_MODE || 'isolated',
        WORKBENCH_ACCOUNT_DATA_DIR: process.env.WORKBENCH_ACCOUNT_DATA_DIR || '/data/accounts',
        WORKBENCH_WA_AUTH_DATA_PATH: process.env.WORKBENCH_WA_AUTH_DATA_PATH || '/data/sessions/wa',
        WORKBENCH_TG_SESSION_DIR: process.env.WORKBENCH_TG_SESSION_DIR || '/data/sessions/tg',
        WORKBENCH_CHROME_STATE_DIR: process.env.WORKBENCH_CHROME_STATE_DIR || '/tmp/workbench-chrome',
        WORKBENCH_WA_CHROME_MIN_AVAILABLE_MB: process.env.WORKBENCH_WA_CHROME_MIN_AVAILABLE_MB || '384',
        WORKBENCH_WA_CHROME_PREFLIGHT: process.env.WORKBENCH_WA_CHROME_PREFLIGHT || '1',
        WORKBENCH_WA_WEB_CACHE_MAX_AGE_HOURS: process.env.WORKBENCH_WA_WEB_CACHE_MAX_AGE_HOURS || '72',
        DBUS_SESSION_BUS_ADDRESS: process.env.DBUS_SESSION_BUS_ADDRESS || '',
        DBUS_SYSTEM_BUS_ADDRESS: process.env.DBUS_SYSTEM_BUS_ADDRESS || '',
        PUPPETEER_EXECUTABLE_PATH: process.env.PUPPETEER_EXECUTABLE_PATH || '/usr/bin/chromium',
        PUPPETEER_SKIP_DOWNLOAD: 'true',
      },
      max_memory_restart: '1536M',
      kill_timeout: 15000,
    },
    {
      name: 'social-workbench-account-supervisor',
      script: 'workers/account-worker-supervisor.js',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        DATA_DIR: process.env.DATA_DIR || '/data',
        WORKBENCH_DB_DIR: process.env.WORKBENCH_DB_DIR || '/data/db',
        WORKBENCH_OUTBOX_DIR: process.env.WORKBENCH_OUTBOX_DIR || '/data/outbox',
        WORKBENCH_ACCOUNT_DB_MODE: process.env.WORKBENCH_ACCOUNT_DB_MODE || 'isolated',
        WORKBENCH_ACCOUNT_DATA_DIR: process.env.WORKBENCH_ACCOUNT_DATA_DIR || '/data/accounts',
        WORKBENCH_ACCOUNT_WORKER_MAX_WORKERS: process.env.WORKBENCH_ACCOUNT_WORKER_MAX_WORKERS || '5',
        WORKBENCH_ACCOUNT_WORKER_MAX_WA: process.env.WORKBENCH_ACCOUNT_WORKER_MAX_WA || '1',
        WORKBENCH_ACCOUNT_WORKER_MAX_TG: process.env.WORKBENCH_ACCOUNT_WORKER_MAX_TG || '4',
        WORKBENCH_CHAT_SYNC_ENABLED: process.env.WORKBENCH_CHAT_SYNC_ENABLED || '1',
        WORKBENCH_LABEL_SYNC_ENABLED: process.env.WORKBENCH_LABEL_SYNC_ENABLED || '1',
        WORKBENCH_SEND_ENABLED: process.env.WORKBENCH_SEND_ENABLED || '0',
        WORKBENCH_CHANNEL_RUNTIME_REQUIRED: process.env.WORKBENCH_CHANNEL_RUNTIME_REQUIRED || '1',
        WORKBENCH_CHROME_STATE_DIR: process.env.WORKBENCH_CHROME_STATE_DIR || '/tmp/workbench-chrome',
        WORKBENCH_WA_CHROME_MIN_AVAILABLE_MB: process.env.WORKBENCH_WA_CHROME_MIN_AVAILABLE_MB || '384',
        WORKBENCH_WA_CHROME_PREFLIGHT: process.env.WORKBENCH_WA_CHROME_PREFLIGHT || '1',
        WORKBENCH_WA_WEB_CACHE_MAX_AGE_HOURS: process.env.WORKBENCH_WA_WEB_CACHE_MAX_AGE_HOURS || '72',
        WORKBENCH_CHANNEL_SYNC_RETRY_BASE_MS: process.env.WORKBENCH_CHANNEL_SYNC_RETRY_BASE_MS || '30000',
        WORKBENCH_CHANNEL_SYNC_RETRY_MAX_MS: process.env.WORKBENCH_CHANNEL_SYNC_RETRY_MAX_MS || '600000',
        DBUS_SESSION_BUS_ADDRESS: process.env.DBUS_SESSION_BUS_ADDRESS || '',
        DBUS_SYSTEM_BUS_ADDRESS: process.env.DBUS_SYSTEM_BUS_ADDRESS || '',
        PUPPETEER_EXECUTABLE_PATH: process.env.PUPPETEER_EXECUTABLE_PATH || '/usr/bin/chromium',
        PUPPETEER_SKIP_DOWNLOAD: 'true',
      },
      max_memory_restart: '512M',
      kill_timeout: 15000,
    },
  ],
};
