module.exports = {
  apps: [
    {
      name: 'social-workbench',
      script: 'server/index.js',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: process.env.PORT || 3000,
        DATA_DIR: process.env.DATA_DIR || '/data',
        WORKBENCH_DB_DIR: process.env.WORKBENCH_DB_DIR || '/data/db',
        SSO_ENABLED: process.env.SSO_ENABLED || 'true',
        SSO_LOGIN_URL: process.env.SSO_LOGIN_URL || 'https://skyline-ark-sso.tyhark.com/login',
        SSO_LOGOUT_URL: process.env.SSO_LOGOUT_URL || 'https://skyline-ark-sso.tyhark.com/logout',
        SSO_REDIRECT_PARAM: process.env.SSO_REDIRECT_PARAM || 'redirect',
        SSO_LOGOUT_REDIRECT_PARAM: process.env.SSO_LOGOUT_REDIRECT_PARAM || 'redirect',
      },
      max_memory_restart: '512M',
      kill_timeout: 5000,
    },
    {
      name: 'social-workbench-login-worker',
      script: 'workers/service-login-worker.js',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        DATA_DIR: process.env.DATA_DIR || '/data',
        WORKBENCH_DB_DIR: process.env.WORKBENCH_DB_DIR || '/data/db',
        WORKBENCH_RAW_DB_PATH: process.env.WORKBENCH_RAW_DB_PATH || '/data/db/raw.sqlite',
        WORKBENCH_RUNTIME_DB_PATH: process.env.WORKBENCH_RUNTIME_DB_PATH || '/data/db/runtime.sqlite',
        WORKBENCH_OUTBOX_DIR: process.env.WORKBENCH_OUTBOX_DIR || '/data/outbox',
        WORKBENCH_WA_AUTH_DATA_PATH: process.env.WORKBENCH_WA_AUTH_DATA_PATH || '/data/sessions/wa',
        WORKBENCH_TG_SESSION_DIR: process.env.WORKBENCH_TG_SESSION_DIR || '/data/sessions/tg',
        PUPPETEER_EXECUTABLE_PATH: process.env.PUPPETEER_EXECUTABLE_PATH || '/usr/bin/chromium',
        PUPPETEER_SKIP_DOWNLOAD: 'true',
      },
      max_memory_restart: '1536M',
      kill_timeout: 15000,
    },
  ],
};
